server:
  port: 8002
spring:
  rabbitmq:
    addresses: 172.16.2.81
    port: 5672
    virtual-host: /rabbitmq-stu
    username: xqs
    password: 1
    connection-timeout: 10000
    template:
      retry:
        enabled: true # 开启连接超时重试机制
        initial-interval: 1000ms # 连接失败后的初始等待时间
        multiplier: 1 # 连接失败后的等待时长倍数，下次等待时长 = (initial-interval) * multiplier
        max-attempts: 3 # 最大重试次数
    publisher-returns: true
    publisher-confirm-type: correlated